import { reset, seed } from 'drizzle-seed';

import { db } from './db';
import * as schema from './schema';

const userIdSeeds = [
  'jMjDsHBbPQO4UaXFzQPNS',
  'oCPdPutVGH5fAJ32qXHRt',
  '-X7-iPJAmIJl8EqfLSu9b',
  'QwmIWWuCkG9cOt5dWzHFD',
  '_JINfnVl8ZunaJhRWxsfP',
  '2zBLvv7Qw92V3CjuI6WPY',
  'BXudqRkt2w1T5e059eY2P',
  'RrPzQoTFIYq6DIgjAo3O_',
  'qqrU9xChx0K7_Sm-oLeb2',
  '-SHg32kTLRPT0DHGUC_xj',
  'iXEdk3mLNs6PfG8d9is1-',
  'CbxQFZ5BgdUwfaO09Yszo',
  '8EznFcmOBQ3MzxI4vXMAh',
  'esz-Q6fRHYVWpkrDwSoIP',
  'T5VYHRP3gfvR7hWA-YZQz',
  'nVx8QbYIOPMcwHdAVRTfb',
  'zlnXky5GIyI_RNKSGy3MN',
  '0n9go6Dvn8q_bf66A5E15',
  'D9O_HT6XrxViDUjlTZcoA',
  '-MY4DGyiKOWeromZOBPG3',
  '9PjPBhg_pNThAPHmFFRVI',
  'ez4ek554X4uSEcXJGNeMm',
  'J5z5HyPz6zd4TkJR74ftR',
  'XnuiWuSWyajAd-fHDAnFw',
  'A0R-haHLsxFeKCT_mx_-S',
  'QFVFFb2ZaNQErzzeRM0Yx',
  '-Fpoli3OCQkLIPh5TrlVJ',
  '0SaxuJSXWw8x7A-0aaSzt',
  'eqPzojhf2G2jUSR2PkWcn',
  'hyKfOT4ELqSpmzDtfu4CF',
  'R8lkvvO4r7YZiw57ie6vL',
  'g6eEU5yfVBJVwnf3iijkT',
  '2ZKjE8zqJ-M8vJV4Tzxli',
  'GnzU-eKi7pVJad-4ATaV8',
  'b4EwzzxZljaM7PPcIU3im',
  'bL6yZRzwy6kLY7xUu-hJG',
  '3ilONheC35ehTsc_zxIeU',
  'gYYJDzgqwYy48ULMNiceJ',
  'poJhvmAtNS3yU5o0kajjE',
  '8-FUl2IQTwqsIhpICWzjL',
  'w1V0x6pKJzoUbJHt-TIeH',
  'eV445ptvnO8eChIy3Y7ix',
  'cNeFMRN_Sfo1ICVfoAiu6',
  'EBzPSqUWpWv8d5ueLCsdy',
  'NIdpWmQeHD6U06ER0zATJ',
  'CLZD1AF2AA0MXxTBLqlYh',
  'tKs-hkbZhkCRfMI6_9_FI',
  'YnOePQvMQKlG3Xyz2A1FH',
  '21VqHyow936qPJzTY1W3U',
  'SlH_NHQRd4OExmEsSzL2O',
  'mKKTHZg_QCwHYa2oN_ymG',
  'E3g1zzuiRPsxNWfIv0sXY',
  '11z_R6gyIFAmuhPUk5nbR',
  'f-4lH9Yky7uYKMgNKfeRw',
  'A_Pbz63QzB-GOeI-hdw5Y',
  '1CQpcWJZo2GFxa19fnkDc',
  'nkXRvkf76vXy-2Q0st-IM',
  'PGuDaQKPPMGBExAvMbrEk',
  'iDwgCyRRotimqHtVPofMS',
  'vDu7jXN0DgeO8D--e5wt7',
  'j0sx7Hy718pbA-tTv2Dx8',
  '03vmvUwQaFMd6j7ya2gSO',
  'PTz1XmfPmFt6su-I7mf_m',
  'SCulRoflD_0oz3Nak3QVK',
  'llp0rpyFYBJ6WxHweIAVZ',
  '3HOeRVV6DuqUkj8WWl_qT',
  'jMupEvC0DnTic6uaerJ3G',
  'rxQ730imFYHmqNpy4HDpD',
  'nNxevqtzkIfI3yjkgFhGE',
  'hi1PpFEpTwA3hMOewTsqy',
  'UkHcEWR4h4ELZGaGlkjOE',
  'fqXquByUaQsK_2_CnBAYw',
  '84tVe8uRMHSCjz6d70v7o',
  'oK-KFP60u5qivO37gt2U0',
  'i3i9-LsSNcjo4YIddVxx8',
  'MANkswvP4V8vIc8wrAEJG',
  'OIh05r574u2ZOiAohl_Nf',
  '2m6MiKXhqsQJvqd6hz2V6',
  'D2FAYqZvpGEQxUaLKJr3T',
  '1L8tnATlGVWjAi54QL7Qi',
  'HLtEsty96ydQZxXZhP5k7',
  'cYk40Duu2Cq4L3jxN4egE',
  '12fy55SDdjV0W0L8wnIte',
  'vPxrEDJH6auGcmzUtoQXH',
  'CbE9EYFcyzhnsvFMFvyqm',
  'azJp_wQ-G0rKqvPSvrhsu',
  'mJWvaNXh070Cocj8JzPLm',
  'wmnMuIp6o3GiwdShn0yXu',
  'VH88gL3t1GCs2AkpmNtVp',
  'vjzvvXMRQdmfMf1gVf_B0',
  'bhH4WuRpNO-AO6KELaXJ5',
  'omD9griyoYAKsv1STwWkR',
  'iV2_u155XLuaztABOLhDE',
  'r-AV96JuRv3BvQYwR5mlC',
  'isMfndixCy3HuQmq2RT5t',
  'OBjBF2_E12gxEuKfXT6oW',
  'jR-lqnON8PWiJ4laVhJ1N',
  'MFkoaLnv8S7ro0aCPzWnw',
  'ee69e9R2y0-VsEFRIBhN6',
  'kCfHGGgPailGQPXSDMYj9',
  'ebe1nVGmXyOhrFQVVLErx',
];

const roomIdSeeds = [
  'OvLK_rsZn1eAaiPQa3w8z',
  '4eOX0TLEHfixOGorVBRoF',
  'kcc4nBtLBXt82hODu9YqF',
  'XwnPegbDTNwBSolJB0d-W',
  'w8amkZr_25BXIIuBwI-_L',
  '9bCy8qluSyRAJA2pqX373',
  'PVQlCqrMPAM60Hd7YucJF',
  'Y0mdHs5rIxEnsqOTVhkZ1',
  'X2jsoEJMJt65CV6I472gZ',
  'KJW0cuYrhdAEt5CegGxtX',
  'rt5jbbmUnw-RtjXtktioT',
  'sAjZeSRu_006OdL9sQC-_',
  'rZKePBvu4_HGCnNKY44bq',
  'sauDqIlQQahxc-ILxdKD2',
  '9Q5yMi8VkkZZCoZeevEQZ',
  'buVGid-Y7L5a0_HGAQQG1',
  'Qlj3qmAN-s084kTv0bL_l',
  '-x2OmOcfBzgLwOqrquHWt',
  'sdYJ-tZ9sa3mdZozvchjt',
  'lppbWAyqkMcFzNvkbb0kV',
  'sBtuBYr0LF09Ywy_Bqk4h',
  'sXKAIt3q3_izd-DOdAAqH',
  'XgqWA9UGuBSfH_3HGBEko',
  'K9eggWcut3pb1M5ST1usD',
  'HXp2YrChLQaOo4y1oN59R',
  'yOah7hDEhjcuOmUnOWHvx',
  'wvRKA7VpfF-RZk_TIdWEA',
  'xGjVfsB7VxA4IOfdPX959',
  'QU9Uu81J2f6TcmefxhS13',
  'J6uxA0d0rZxva9_Pi68aY',
  'wM4NmuByNjO9JB6CwRrhF',
  'H3-zsIMtP57iGDJmDYwee',
  'NvYV49SAK6SV5V4J184BP',
  'VNyqculRe55W6zYC_ofah',
  '5TpA7TatvaRWms5RZi7Ie',
  'spEqJMEJu0-tE6-T7afiv',
  'SSmjghEtRGrwTA7i-4wFR',
  'uRPVphS-G8wbuLPIiiNow',
  '0gJ-YMtw7mctO80aGQKa3',
  'YaV-7sduKv3752AqlAhhi',
  'tqHTAuotQo1z-pvg5ZGRC',
  'XfSgOmAudSjUcsm-Umcex',
  'pSqxYxlXK1UtVKuwt6osp',
  'ZEsI7CCclODidCdLQoI9w',
  'L8fNyyKsy73aEtrMHEDJ8',
  'ekesCZTIAleW-XosUwz4R',
  'cKJ4w9IfCXEDDE-_ZCM2F',
  '6wo7L37g040tn1w27-Mfy',
  'GGQnYNZIwjOfp5KlU5sWI',
  'JOydMpNZl0Lg4SCkSNxIg',
];

const stateNames = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const seedDb = async () => {
  // seed
  reset(db, schema);
  console.log('db reset');

  const passwordHash = await Bun.password.hash('password123');

  await seed(db, schema).refine(funcs => {
    return {
      chats: {
        count: 0,
      },
      rooms: {
        columns: {
          id: funcs.valuesFromArray({ isUnique: true, values: roomIdSeeds }),
          name: funcs.valuesFromArray({ isUnique: true, values: stateNames }),
        },
        count: 50,
      },
      users: {
        columns: {
          displayName: funcs.firstName({ isUnique: true }),
          email: funcs.email(),
          id: funcs.valuesFromArray({ isUnique: true, values: userIdSeeds }),
          passwordHash: funcs.default({ defaultValue: passwordHash }),
        },
        count: 50,
        with: {
          rooms: 1,
        },
      },
    };
  });

  await db.insert(schema.users).values({ displayName: 'Harris', email: 'harris@email.com', passwordHash });
  await db.insert(schema.users).values({ displayName: 'Other', email: 'other@email.com', passwordHash });

  console.log('db seeded!');
};

await seedDb();
