volumes:
  db-data:
  redis-data:
  jaeger-data:
  localstack-data:
  prometheus-data:
  grafana-data:
  loki-data:

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: scaled_chat_app
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432 # exposed for migrations from local
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379 # exposed for redis' dashboard
      - 8001:8001
    restart: always
    volumes:
      - redis-data:/data

  # localstack:
  #   container_name: localstack-main
  #   image: localstack/localstack
  #   ports:
  #     - 127.0.0.1:4566:4566 # LocalStack Gateway
  #     - 127.0.0.1:4510-4559:4510-4559 # external services port range
  #   # environment:
  #   #   # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #   #   - DEBUG=${DEBUG:-0}
  #   volumes:
  #     - localstack-data:/var/lib/localstack
  #     - /var/run/docker.sock:/var/run/docker.sock # ???

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount the config file
      - prometheus-data:/prometheus # Persistent storage for metrics
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default admin password (change in production)

  loki:
    image: grafana/loki:latest
    container_name: loki
    # command: -config.file=/etc/loki/config.yaml
    volumes:
      # - ./loki-config.yaml:/etc/loki/config.yaml
      - loki-data:/loki

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    restart: on-failure:3

  server:
    build: ./server
    depends_on:
      - postgres
      - redis
      - loki
      - grafana
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/scaled_chat_app?sslmode=disable
      LOKI_URL: http://loki:3100
      OTLP_TRACES_URL: http://jaeger:4318/v1/traces
      PORT: 3000
      REDIS_URL: redis://redis:6379
      S3_URL: http://localstack-main:4566
    restart: on-failure:3
    # deploy:
    #   replicas: 4

  client:
    build: ./client
    container_name: client
    restart: on-failure:3
    depends_on:
      - server

  httpd:
    build: ./httpd
    container_name: httpd
    depends_on:
      - server
      - client
    ports:
      - 80:80
    restart: on-failure:3
