import { db } from './src/db';
import { users } from './src/db/schema';

const randomChatGptGeneratedPhrases = [
  'moment adventure path rain glow magic river',
  'rain wonder story whisper cloud',
  'flower whisper time',
  'bright friend glow cloudy wind',
  'blue friend light flower',
  'glow secret moment flower',
  'coffee storm cloud moment forest light flower',
  'dream friend flower whisper',
  'star stone echo coffee hope rain magic',
  'star voice path dreamer song running bright',
  'hope river bright dream coffee storm',
  'glow stone fire running shadow glow glow',
  'voice moment blue adventure journey dreamer',
  'whisper dreamer journey sky spark flower happy',
  'shadow heart memory path storm sky blue',
  'tree sky soul running',
  'glow sky secret journey voice secret adventure',
  'river wind fire',
  'heart storm song music adventure journey wind',
  'wonder music music',
  'music song dance',
  'tree song coffee',
  'mountain secret rain wind whisper',
  'mountain spark shadow adventure star',
  'running cloud ocean sunset friend time',
  'adventure journey fire time',
  'forest voice echo',
  'dance smile rain path shadow flower',
  'fire shadow shadow',
  'secret laugh coffee soul',
  'echo song rain happy',
  'spark fire mountain cloudy',
  'laugh flower sunset forest song spark',
  'song laugh laugh journey',
  'rain cloudy soul',
  'whisper laugh river star music memory friend',
  'soul hope light time moment journey river',
  'stone music bright',
  'coffee time heart wonder dance',
  'heart journey sky future blue',
  'ocean sky future',
  'secret smile laugh rain future friend voice',
  'wonder cloud path tree secret song spark',
  'flower star ocean',
  'secret star stone soul',
  'ocean shadow moment coffee smile',
  'happy glow music rain',
  'secret spark laugh',
  'flower friend whisper moment',
  'cloudy wonder spark',
  'running fire ocean',
  'magic future soul smile mountain',
  'forest cloudy blue happy river',
  'hope blue cloudy shadow storm laugh',
  'path forest path',
  'heart dream happy rain',
  'whisper friend adventure cloudy',
  'blue friend secret adventure friend',
  'dance future music bright shadow',
  'heart wind journey flower friend',
  'river happy moment light dance',
  'story dance hope friend whisper',
  'smile whisper light soul',
  'fire friend dream fire',
  'storm flower path',
  'voice river wind',
  'storm dreamer tree star wonder',
  'fire star happy cloudy voice rain wonder',
  'star echo running spark',
  'flower friend music glow running song',
  'dream heart smile hope coffee',
  'secret moment bright light moment moment happy',
  'wind mountain dance voice dream flower',
  'smile happy sunset ocean whisper',
  'path happy glow cloudy',
  'song secret friend song dream journey soul',
  'shadow storm sky light smile path echo',
  'echo cloudy forest mountain future running',
  'whisper mountain friend song spark bright heart',
  'laugh bright heart time tree mountain stone',
  'bright shadow coffee star voice shadow secret',
  'mountain light cloud star cloudy dance',
  'happy echo cloud magic moment wonder',
  'journey forest path running spark music voice',
  'laugh cloudy happy memory',
  'sky soul story',
  'future flower journey sky',
  'rain mountain journey dreamer soul sunset happy',
  'river spark cloudy hope whisper',
  'voice light time running adventure music sky',
  'voice tree light laugh friend',
  'magic cloudy laugh time',
  'light light future flower ocean',
  'music running flower mountain wind running',
  'echo moment voice laugh',
  'dream star happy echo',
  'dance heart dreamer dreamer star memory',
  'dream voice wind',
  'memory wonder stone running smile forest smile',
  'tree heart magic laugh spark',
  'secret running forest cloud whisper',
  'magic fire flower',
  'mountain stone wind memory hope',
  'soul soul wonder sky',
  'adventure dance wind coffee',
  'echo fire wonder moment moment coffee ocean',
  'sunset tree journey',
  'river laugh river tree',
  'voice time future mountain',
  'fire fire journey tree smile dream',
  'tree dream rain star storm',
  'dreamer blue heart sky heart light wonder',
  'spark fire secret',
  'laugh memory voice dreamer cloudy sky blue',
  'time ocean glow tree glow dance light',
  'tree memory moment friend',
  'dance tree secret river laugh',
  'hope forest forest',
  'moment bright dreamer',
  'mountain blue wind',
  'dream magic future rain glow',
  'spark wind soul whisper',
  'song forest storm heart coffee',
  'song magic magic glow star dance heart',
  'storm sunset music',
  'dream shadow laugh light laugh soul',
  'mountain spark coffee heart',
  'sunset light blue heart wonder story',
  'heart coffee glow',
  'journey moment song',
  'glow wind dreamer',
  'secret light secret sunset ocean storm',
  'laugh light bright',
  'secret wonder magic secret dreamer wonder',
  'storm ocean mountain storm story music',
  'voice path fire adventure',
  'memory moment blue moment cloudy',
  'sunset smile heart echo glow rain',
  'journey dance sky hope',
  'tree path mountain running',
  'heart whisper coffee',
  'river spark moment forest dance secret',
  'dream rain dream rain running stone spark',
  'star time whisper whisper tree wind friend',
  'hope blue cloudy secret magic heart adventure',
  'mountain star secret coffee',
  'song future future dream',
  'whisper fire dreamer',
  'heart laugh whisper shadow fire',
  'fire journey mountain spark tree',
  'laugh tree friend heart wonder',
  'dreamer journey tree mountain heart heart tree',
  'dream magic dream magic magic',
  'echo bright dance',
  'shadow future fire story secret cloud stone',
  'stone shadow flower bright story cloud spark',
  'magic blue bright spark fire wind',
  'mountain magic echo magic',
  'cloud whisper shadow echo stone',
  'glow smile story song storm',
  'story moment coffee',
  'echo blue laugh song heart',
  'secret coffee storm magic story rain',
  'secret glow stone rain',
  'bright happy magic future',
  'coffee storm forest sky mountain',
  'spark path mountain rain spark sky happy',
  'wind star rain tree soul star',
  'sunset running secret moment light',
  'journey ocean fire',
  'coffee happy shadow dreamer glow',
  'memory story voice',
  'forest future spark rain friend ocean',
  'light spark shadow journey hope hope time',
  'memory whisper time path glow happy mountain',
  'moment hope echo story song',
  'laugh voice sunset',
  'journey mountain memory smile soul voice sky',
  'music friend river memory magic',
  'heart bright tree stone whisper voice',
  'cloudy cloud wind sunset smile cloud bright',
  'sky mountain whisper friend fire glow story',
  'rain flower cloudy mountain wonder glow stone',
  'tree star tree ocean glow echo',
  'path fire shadow secret',
  'cloud shadow cloud hope laugh echo future',
  'adventure cloud friend secret',
  'stone star future sky flower magic',
  'song hope light music',
  'sky happy time journey sky memory ocean',
  'forest path wonder',
  'forest river light flower memory forest dreamer',
  'memory bright glow laugh storm adventure river',
  'sunset shadow blue',
  'heart time happy path',
  'tree memory heart smile sky spark friend',
  'storm dream tree',
  'wonder stone friend storm tree',
  'tree tree journey',
  'ocean future memory story adventure',
  'music dreamer echo',
  'forest adventure storm dance coffee',
  'music sunset flower bright',
  'magic heart whisper fire tree voice storm',
  'spark sky glow sunset soul',
  'tree secret dream blue cloud bright',
  'smile forest hope laugh friend magic',
  'wonder echo whisper ocean',
  'voice voice wonder',
  'spark journey forest',
  'star cloud bright forest sunset time',
  'sky cloudy path forest',
  'journey light friend memory',
  'music ocean storm music mountain magic',
  'voice soul secret time',
  'journey running running story sky cloudy dance',
  'time bright mountain',
  'coffee stone shadow shadow glow adventure',
  'moment flower memory sky hope',
  'forest light voice adventure',
  'tree ocean soul running',
  'forest rain stone',
  'sunset echo journey blue shadow',
  'wind friend stone voice star rain',
  'laugh cloud ocean smile laugh future',
  'sky whisper friend ocean whisper rain sunset',
  'echo rain wonder glow',
  'memory wonder shadow adventure',
  'magic time smile glow',
  'running storm cloudy spark',
  'star tree adventure smile dreamer',
  'bright ocean stone',
  'flower flower mountain stone story wonder',
  'spark wonder storm dream mountain tree',
  'shadow laugh running future bright cloud',
  'rain cloud sunset memory',
  'laugh running secret',
  'voice story bright adventure fire laugh',
  'light wind smile dream flower',
  'echo bright path tree future cloudy happy',
  'river cloudy mountain',
  'hope journey fire sunset hope friend happy',
  'adventure memory river adventure magic happy blue',
  'whisper voice tree future echo',
  'fire happy star flower memory whisper',
  'running song mountain soul journey coffee',
  'shadow hope echo tree sunset shadow',
  'hope blue magic secret shadow wonder',
  'ocean adventure blue',
  'laugh soul tree music',
  'adventure journey star moment time',
  'dreamer rain voice voice adventure storm',
  'ocean voice journey',
  'whisper cloud hope fire mountain spark sunset',
  'shadow dream time',
  'time echo tree',
  'memory song star song wonder',
  'running smile storm blue laugh blue bright',
  'memory soul heart mountain coffee star',
  'blue spark shadow song memory',
  'flower light happy sky echo',
  'secret voice memory cloud hope path',
  'fire voice time',
  'tree echo moment cloud heart',
  'secret stone soul cloudy magic future storm',
  'whisper moment wonder coffee friend memory echo',
  'stone shadow shadow spark',
  'blue secret blue stone storm',
  'time laugh forest fire journey',
  'dance river coffee path dream magic',
  'friend wind cloudy',
  'sky storm forest',
  'path dream storm glow heart',
  'voice ocean cloudy glow',
  'fire wind secret forest moment spark running',
  'river flower mountain coffee',
  'spark blue sunset light blue stone glow',
  'light running music',
  'echo wonder running',
  'song glow stone',
  'glow fire rain song tree soul sky',
  'tree laugh wonder flower path moment wonder',
  'ocean wonder happy cloud story mountain',
  'glow voice fire future stone glow',
  'blue glow light cloud whisper',
  'coffee river friend',
  'laugh dance future flower adventure light',
  'star dance echo star',
  'song echo hope wind magic song heart',
  'path light mountain future ocean dance',
  'secret star sky music moment star',
  'friend memory storm glow heart story voice',
  'flower journey heart star whisper',
  'shadow memory time soul cloud cloudy',
  'voice heart shadow path sunset',
  'song secret soul',
  'adventure star time heart echo echo',
  'ocean forest dream happy hope river',
  'journey hope rain',
  'laugh memory star shadow sky path',
  'bright shadow running whisper music',
  'hope journey time happy song future hope',
  'voice future future mountain',
  'song sunset music moment future sunset',
  'hope happy light storm cloud hope',
  'forest cloudy story',
  'light moment song dance dream star coffee',
  'music smile ocean',
  'voice coffee music',
  'secret future voice dream sky',
  'forest dreamer echo mountain stone happy',
  'tree moment dreamer dreamer',
  'glow happy tree storm friend song',
  'cloud wind light sunset friend',
  'story forest voice dreamer wind shadow',
  'blue ocean song song happy river dream',
  'time adventure dreamer running mountain shadow future',
  'whisper tree time flower happy wonder',
  'glow dance fire blue',
  'friend shadow story ocean music light',
  'friend time path river',
  'whisper heart forest',
  'mountain whisper ocean adventure tree secret',
  'wonder cloud memory tree path',
  'magic running ocean star path song rain',
  'cloudy whisper fire cloud cloudy tree',
  'dance heart smile future',
  'star river ocean storm journey memory ocean',
  'adventure fire sunset',
  'glow soul music journey memory',
  'smile stone time spark ocean',
  'time hope star shadow rain voice',
  'whisper mountain star',
  'storm memory laugh river journey',
  'secret rain dance memory ocean',
  'hope ocean song',
  'cloud flower ocean heart',
  'story whisper music',
  'hope cloudy spark dance sky wind',
  'secret tree echo time future memory shadow',
  'rain moment magic soul echo dreamer flower',
  'wonder bright sunset adventure moment path',
  'spark spark heart voice bright moment dreamer',
  'secret rain whisper laugh',
  'dance glow mountain story bright song',
  'song river memory',
  'hope cloudy friend song soul',
  'bright dance story storm sunset story',
  'fire soul stone',
  'cloud mountain sunset hope story',
  'cloudy river running stone future',
  'wonder rain soul',
  'star moment coffee',
  'tree song mountain heart',
  'dance star forest sunset song whisper',
  'whisper light sky flower smile wind',
  'future friend secret running star',
  'secret magic blue',
  'echo coffee voice path',
  'whisper friend tree',
  'friend glow running music forest forest star',
  'story voice dream dream sunset ocean mountain',
  'storm laugh happy forest glow',
  'adventure whisper heart tree magic music song',
  'time dance path soul',
  'future laugh future magic spark rain',
  'moment dance future glow smile',
  'secret hope future',
  'spark music sunset',
  'blue mountain adventure whisper',
  'voice sky sky ocean',
  'dance future future story echo',
  'running tree wonder running blue secret',
  'wonder light journey adventure',
  'stone heart glow bright',
  'dreamer memory dream',
  'story bright shadow',
  'hope light friend path tree star storm',
  'running secret heart stone',
  'smile wonder future ocean',
  'whisper journey coffee path fire',
  'fire cloudy blue flower wind forest storm',
  'future laugh forest cloudy cloudy',
  'sunset mountain time memory song wonder time',
  'soul path dream stone voice',
  'ocean sky wind flower',
  'sunset future light',
  'flower music river voice',
  'hope song sunset blue ocean heart',
  'bright shadow dream journey',
  'fire song wonder soul',
  'blue happy dance',
  'tree smile voice',
  'glow light happy magic glow flower',
  'running music dance',
  'running soul whisper hope bright forest song',
  'journey stone ocean secret rain echo path',
  'echo echo dance soul shadow',
  'path magic forest music running friend spark',
  'glow ocean cloudy flower rain river',
  'light spark dreamer laugh star memory coffee',
  'adventure dreamer fire glow cloudy',
  'stone echo dream flower',
  'whisper heart dance dance wind music coffee',
  'friend heart adventure music secret bright',
  'dance memory cloud happy forest',
  'adventure echo dreamer soul coffee',
  'spark rain glow cloudy music bright memory',
  'stone blue wonder forest',
  'river future bright star light cloud sky',
  'soul happy sky music dreamer hope music',
  'friend friend soul dreamer',
  'secret flower forest voice',
  'laugh laugh laugh heart memory wind',
  'song mountain whisper',
  'heart cloudy story cloudy journey',
  'future journey spark secret forest cloud laugh',
  'journey dreamer mountain music running river future',
  'rain whisper secret',
  'laugh sky light journey',
  'spark glow dream bright secret flower',
  'forest sky music fire',
  'blue magic running adventure shadow',
  'memory friend dream running running happy wonder',
  'smile rain hope',
  'memory cloudy hope friend cloudy',
  'friend time whisper happy',
  'running adventure cloudy story sunset cloud',
  'path wind dreamer bright',
  'wind sky dream',
  'tree voice river time',
  'cloud coffee mountain wonder spark',
  'time memory friend cloudy story moment',
  'sunset spark wind flower dance dance coffee',
  'forest running wonder mountain',
  'cloudy dream magic laugh path music',
  'river dream ocean spark sunset secret tree',
  'fire bright dreamer mountain sky moment hope',
  'adventure wonder light tree',
  'coffee journey cloud friend path',
  'happy music bright echo flower dream fire',
  'river dance friend rain',
  'bright cloudy journey echo running',
  'forest friend dream river hope',
  'dream hope heart echo',
  'fire forest ocean mountain song moment',
  'star friend magic journey happy sunset',
  'soul happy forest',
  'path coffee voice blue sky tree sky',
  'stone glow star coffee fire music dreamer',
  'music moment running storm heart',
  'journey cloudy storm dance',
  'friend echo dreamer cloudy flower dance rain',
  'storm friend magic sunset wonder coffee whisper',
  'whisper dream path time cloudy story',
  'dream hope dance',
  'storm star heart echo happy cloudy rain',
  'light storm future flower hope',
  'adventure blue time',
  'secret echo stone',
  'hope light adventure whisper hope wind wonder',
  'sunset star magic cloud tree moment tree',
  'laugh memory echo',
  'coffee moment soul shadow flower',
  'wind bright blue dream time',
  'voice glow storm journey cloudy',
  'whisper shadow sunset running whisper',
  'heart story wonder star dream stone mountain',
  'wind echo light',
  'secret spark friend cloudy time forest',
  'stone music secret',
  'adventure storm wonder adventure laugh',
  'dreamer wind spark future blue happy dreamer',
  'happy soul coffee',
  'fire path stone',
  'friend moment glow whisper',
  'laugh dance path',
  'forest running song storm',
  'ocean echo dance',
  'dreamer tree friend',
  'memory voice wonder smile coffee',
  'echo tree story spark fire smile',
  'happy journey smile stone light forest',
  'music flower voice spark shadow wind coffee',
  'river wonder hope dreamer light',
  'flower running forest',
  'soul song happy',
  'dreamer shadow cloud cloud shadow sky journey',
  'spark wind smile future cloud',
  'star secret happy time whisper',
  'flower whisper happy',
  'forest cloud dance star shadow',
  'path ocean journey hope song glow light',
  'spark dream wind',
  'storm mountain time ocean sunset echo soul',
  'happy fire glow friend sky adventure cloud',
  'secret sky path stone friend',
  'cloudy wonder soul hope',
  'light story star smile',
  'shadow moment dreamer soul',
  'shadow storm story wonder dreamer',
  'journey cloud coffee bright heart dream shadow',
  'music fire journey',
  'heart memory sunset',
  'time journey mountain glow friend friend',
  'story spark blue',
  'smile happy echo stone river sunset ocean',
  'future laugh moment shadow hope sunset adventure',
  'tree echo sunset cloudy',
  'stone whisper wonder bright river tree',
  'fire fire memory river light',
  'blue story storm story tree',
  'star music storm mountain flower',
  'whisper storm storm',
  'magic wind stone bright journey',
  'adventure blue spark',
  'echo light bright blue glow echo sky',
  'cloud voice secret',
  'rain soul magic',
  'friend sky glow dance dreamer',
  'glow whisper laugh',
  'moment rain cloudy future journey magic wonder',
  'glow dance heart cloudy running glow echo',
  'shadow sunset soul coffee',
  'shadow time storm forest',
  'bright bright path',
  'dream whisper sunset adventure whisper wonder friend',
  'magic whisper cloudy soul forest',
  'story flower friend time',
  'laugh light cloud mountain forest wonder memory',
  'whisper stone wind cloud dream music laugh',
  'magic music hope stone',
  'sky time rain voice adventure river',
  'path dance cloudy',
  'glow smile heart spark ocean running',
  'cloudy ocean rain mountain forest journey',
  'dance ocean spark ocean voice',
  'glow voice friend dance time river stone',
  'soul song song story running',
  'glow time memory happy',
  'rain fire ocean smile tree dance stone',
  'whisper cloud heart adventure',
  'moment river running journey soul',
  'magic river adventure ocean',
  'laugh forest coffee friend moment',
  'voice dreamer dream dance',
  'cloudy rain forest wonder sunset mountain future',
  'rain wind story light laugh fire tree',
  'forest star spark heart',
  'river music blue friend cloud river future',
  'laugh whisper glow river river',
  'song hope path hope blue',
  'soul smile echo music',
  'dance moment time laugh stone moment star',
  'happy forest bright friend story moment memory',
  'heart sunset music',
  'cloudy echo happy tree storm mountain cloudy',
  'cloud river time coffee',
  'whisper future tree bright',
  'song song star',
  'mountain hope running stone storm sky friend',
  'tree tree song secret smile voice bright',
  'river fire stone',
  'magic echo voice secret blue running music',
  'rain light spark tree future',
  'storm memory river bright magic happy cloud',
  'shadow adventure blue sunset sunset',
  'hope glow mountain hope memory',
  'spark echo heart',
  'voice bright music bright',
  'fire storm journey',
  'blue journey whisper blue echo happy',
  'river rain happy ocean wonder',
  'cloudy fire glow',
  'ocean memory sunset running storm',
  'glow music cloud memory light moment',
  'flower cloud sky dream laugh flower',
  'tree friend wonder',
  'coffee shadow music laugh',
  'sunset running memory echo cloudy',
  'river laugh storm dream cloudy hope',
  'storm memory mountain',
  'forest fire time voice',
  'sky soul friend dance',
  'sky ocean smile storm storm sky cloudy',
  'voice forest wonder wonder running voice',
  'bright dance tree spark',
  'memory story soul',
  'fire secret bright',
  'ocean stone mountain bright cloud path',
  'cloud coffee dance sunset',
  'running sunset wonder',
  'secret dance tree happy running star voice',
  'dream future light story wind cloud secret',
  'adventure light story dreamer soul',
  'path hope wind river',
  'friend storm dreamer shadow wind song adventure',
  'song forest laugh',
  'running smile memory happy coffee echo',
  'hope adventure moment time',
  'time whisper ocean river ocean fire',
  'dance dance running adventure moment flower light',
  'coffee story wind soul dream tree mountain',
  'heart ocean laugh sky wind',
  'magic whisper heart path rain happy',
  'blue flower memory song story wonder',
  'smile flower memory sky story',
  'path dream fire adventure story laugh cloud',
  'spark ocean spark moment hope',
  'voice story flower cloud echo stone',
  'smile tree soul shadow hope spark cloud',
  'spark heart flower',
  'bright voice flower adventure',
  'light dance fire path voice journey',
  'cloudy dreamer rain river river cloudy cloud',
  'cloud voice rain blue wonder magic laugh',
  'coffee story laugh',
  'journey storm song mountain heart friend spark',
  'friend friend song music star heart',
  'star flower glow',
  'cloud shadow wonder',
  'hope soul smile stone bright',
  'wind path ocean river',
  'heart song storm fire smile dance coffee',
  'wonder memory journey secret adventure heart laugh',
  'heart spark dreamer echo',
  'journey river hope running happy wind',
  'journey memory light path bright dreamer cloud',
  'soul river wind magic blue fire',
  'path star soul echo',
  'soul sunset secret rain dream dream heart',
  'moment sky laugh',
  'story spark cloudy bright stone sunset light',
  'star hope spark blue',
  'dreamer wind hope stone wind sky whisper',
  'friend wind running sky',
  'sky stone happy music time flower',
  'dream laugh cloudy star',
  'voice glow happy light',
  'running whisper bright',
  'soul fire voice journey heart soul',
  'voice whisper cloud fire bright blue',
  'flower friend running spark fire',
  'bright dream secret cloud story dance',
  'soul hope mountain star',
  'ocean wind mountain time',
  'laugh running ocean',
  'wind cloud soul rain dance',
  'secret magic moment storm',
  'flower sky voice magic',
  'tree dreamer journey flower smile',
  'echo dreamer flower story soul',
  'song path dance blue wind adventure',
  'memory flower future',
  'voice sunset cloud',
  'cloud secret laugh memory future magic',
  'laugh song tree cloudy light dream story',
  'star spark wonder storm',
  'mountain bright smile cloudy star',
  'spark magic bright heart whisper',
  'forest whisper secret memory',
  'journey stone coffee mountain whisper path spark',
  'stone heart moment moment cloud',
  'secret dance moment path mountain spark echo',
  'time happy future cloud',
  'rain hope echo magic star voice running',
  'song song secret spark journey flower',
  'voice whisper friend',
  'mountain sunset coffee secret magic memory sky',
  'forest future heart river',
  'future hope soul whisper stone forest wind',
  'storm shadow secret',
  'music blue star blue moment light journey',
  'laugh hope music',
  'cloud stone whisper future ocean',
  'river secret happy whisper path smile spark',
  'cloudy soul shadow mountain friend shadow fire',
  'tree story memory time dance rain time',
  'dance sunset bright dreamer tree',
  'smile mountain tree friend echo laugh',
  'heart star cloudy smile',
  'soul bright voice voice',
  'forest flower cloud magic secret smile',
  'flower dream spark',
  'bright stone memory spark glow',
  'smile fire story',
  'dreamer ocean time rain story flower',
  'friend adventure river flower running soul',
  'mountain happy story wonder whisper',
  'music tree adventure light hope',
  'bright laugh future shadow',
  'forest ocean blue blue wind dreamer',
  'glow journey spark whisper star laugh fire',
  'storm soul stone hope',
  'echo forest whisper path glow happy friend',
  'song memory happy',
  'sky time storm running rain',
  'dreamer soul running hope smile song',
  'forest story smile',
  'wind ocean rain song heart music smile',
  'ocean song dream heart whisper friend light',
  'secret river forest storm friend coffee',
  'shadow adventure future',
  'running star wind wonder shadow adventure',
  'dreamer shadow memory',
  'wind magic soul sunset memory heart rain',
  'cloudy future rain magic forest',
  'soul hope story',
  'dance river storm forest music light smile',
  'whisper running magic',
  'light story rain',
  'whisper path fire cloudy moment story',
  'light blue story ocean dreamer mountain echo',
  'sunset sunset voice flower',
  'wind memory flower shadow cloudy cloud friend',
  'sky glow echo bright wonder',
  'story hope smile',
  'voice moment dreamer spark smile sunset tree',
  'time future happy heart storm',
  'secret wonder spark',
  'sky path hope',
  'sky sunset song bright',
  'mountain dreamer cloud blue path glow',
  'future blue memory',
  'adventure running happy echo time',
  'flower magic tree voice journey',
  'magic story story story',
  'coffee coffee ocean whisper',
  'forest forest forest smile moment music',
  'cloudy sky future wind glow heart cloudy',
  'time time time secret star',
  'soul story happy stone',
  'ocean mountain journey',
  'song ocean ocean cloudy sky forest storm',
  'laugh spark shadow forest friend rain',
  'dreamer rain stone dance echo coffee',
  'ocean friend coffee voice',
  'time forest laugh memory soul',
  'coffee ocean rain magic',
  'star sky rain running echo music',
  'echo heart soul dream',
  'glow hope whisper bright wind stone',
  'glow friend flower sky',
  'fire future magic coffee wonder',
  'music cloud cloudy sky fire shadow wind',
  'whisper star flower tree',
  'happy adventure memory adventure',
  'time blue wonder cloudy',
  'memory cloud river',
  'heart magic dreamer story cloudy magic',
  'storm heart storm river shadow star',
  'friend light hope dream light',
  'spark fire star',
  'running glow running running star bright wonder',
  'path friend light dreamer rain',
  'coffee secret adventure forest',
  'secret forest whisper coffee bright running coffee',
  'blue moment soul ocean stone river blue',
  'forest magic sunset secret',
  'voice smile path coffee time',
  'story stone shadow dance time journey sunset',
  'magic cloudy memory fire',
  'future happy star journey fire storm soul',
  'river cloud cloud',
  'secret wind time cloud dreamer',
  'forest future song storm music shadow',
  'shadow star voice moment secret rain moment',
  'mountain mountain laugh light',
  'spark sunset star sunset sunset happy',
  'wonder dreamer cloud wonder stone',
  'river spark secret sky sunset smile',
  'river sunset hope',
  'bright cloud light journey cloud',
  'mountain forest dreamer wonder forest forest cloudy',
  'sunset cloud wonder ocean journey river wind',
  'whisper path smile magic moment',
  'smile coffee forest tree tree sunset coffee',
  'wind dream heart fire',
  'dance story sunset voice stone friend',
  'stone stone star star fire river',
  'heart music moment adventure sky',
  'forest rain river music stone heart',
  'tree fire laugh stone laugh journey ocean',
  'cloudy moment mountain',
  'cloudy river wonder whisper',
  'mountain rain path moment wonder soul adventure',
  'magic path fire ocean',
  'heart cloud coffee',
  'light river cloudy future journey sky tree',
  'bright spark river story cloudy stone dreamer',
  'laugh river stone wind star star stone',
  'friend laugh soul mountain coffee sky',
  'hope hope glow cloudy dance laugh heart',
  'blue star flower future',
  'wonder glow fire memory whisper hope soul',
  'flower friend star smile storm flower',
  'song laugh adventure glow mountain',
  'sunset laugh fire shadow',
  'future sunset ocean',
  'echo bright flower sky happy happy story',
  'magic glow friend glow wind',
  'friend blue happy',
  'song star memory memory river',
  'spark happy bright',
  'storm music tree light dreamer spark star',
  'fire shadow blue soul glow rain',
  'memory flower secret journey moment friend',
  'river friend hope sunset',
  'smile future forest path',
  'tree tree fire moment memory bright light',
  'heart friend music laugh stone',
  'wind sky rain blue memory shadow',
  'journey future stone running',
  'friend whisper blue heart laugh',
  'blue story path laugh',
  'flower cloudy smile flower future',
  'star spark ocean memory',
  'path soul heart path coffee flower heart',
  'dream magic path',
  'hope running storm bright star shadow',
  'path river glow',
  'whisper path spark shadow hope',
  'heart future song sunset dream blue hope',
  'star star future shadow blue',
  'journey glow forest sunset stone sunset',
  'running fire flower bright future dance',
  'happy laugh cloud hope magic',
  'sky laugh cloudy fire',
  'magic echo hope magic cloud',
  'path music storm music echo wind dream',
  'blue hope spark fire',
  'laugh happy sky fire song',
  'light echo music magic bright dream time',
  'dream wind forest cloud',
  'coffee journey storm',
  'path song heart stone light',
  'song running soul storm',
  'glow wonder magic dance cloud forest',
  'smile moment voice storm journey mountain',
  'sky tree bright shadow forest',
  'storm running glow bright soul song',
  'tree story laugh blue heart',
  'shadow happy journey blue future adventure stone',
  'sunset light coffee path moment path',
  'dream coffee blue shadow rain voice tree',
  'cloudy magic light',
  'flower tree hope magic',
  'journey friend blue wonder wonder river',
  'ocean moment secret light',
  'shadow magic sunset',
  'heart dream journey',
  'song running smile tree friend',
  'river cloudy rain',
  'river hope moment',
  'glow time rain story happy happy',
  'wonder spark happy wind sunset',
  'path memory sky glow',
  'echo star fire wonder story secret',
  'flower bright music forest story future song',
  'future bright flower wind soul',
  'blue storm fire forest forest',
  'hope blue friend dance sunset',
  'hope river light',
  'friend fire shadow whisper dream river',
  'happy heart song journey',
  'tree voice moment path time',
  'river moment ocean',
  'music river smile',
  'adventure dreamer flower happy tree',
  'song echo story friend adventure ocean music',
  'shadow future moment dreamer',
  'hope cloudy mountain ocean fire hope',
  'cloudy hope fire',
  'adventure sunset spark dreamer story dreamer',
  'shadow path happy time smile coffee sky',
  'mountain glow future rain sky',
  'dance running dreamer adventure coffee river',
  'hope rain fire storm adventure spark',
  'coffee running magic voice',
  'memory whisper dreamer magic music stone',
  'tree memory adventure happy wind story',
  'cloud hope dreamer sky rain',
  'magic running dance running',
  'ocean cloudy hope forest',
  'path fire journey',
  'path dreamer dreamer future dance',
  'storm secret flower',
  'laugh glow path tree moment light',
  'magic smile adventure time star star river',
  'time mountain path smile story future',
  'shadow laugh time stone rain journey happy',
  'whisper shadow dreamer shadow sunset dream stone',
  'soul tree river sunset mountain sunset flower',
  'river heart dreamer smile sunset glow',
  'stone voice song cloudy blue hope mountain',
  'time cloudy cloudy',
  'sky running shadow voice soul',
  'glow fire coffee moment adventure',
  'forest music ocean',
  'voice secret sky laugh',
  'music story cloud stone music bright flower',
  'happy rain journey friend echo time',
  'memory light fire',
  'light heart cloudy future cloud',
  'fire wonder flower',
  'ocean flower journey ocean whisper wonder coffee',
  'flower river echo running hope wind',
  'coffee smile mountain whisper time moment spark',
  'music ocean soul echo path',
  'shadow smile spark cloud cloud',
  'wonder flower dream shadow friend star star',
  'echo moment dance spark friend time',
  'adventure echo moment spark',
  'coffee moment cloudy wind moment river',
  'hope ocean coffee running adventure star dreamer',
  'bright friend story bright laugh journey',
  'music tree echo hope star cloudy',
  'spark coffee path heart adventure',
  'future friend river smile',
  'path river happy',
  'happy future journey cloud sky secret heart',
  'forest whisper sunset',
  'cloudy journey echo memory sky blue',
  'voice dreamer spark cloud stone fire light',
  'shadow flower adventure wind wonder smile storm',
  'moment dream forest',
  'music path voice soul smile',
  'secret whisper flower shadow',
  'light smile memory',
  'river stone tree forest dream dance wind',
  'dream storm forest star moment music',
  'light sky fire tree ocean cloud',
  'sunset friend adventure echo',
  'moment wonder shadow path bright future',
  'adventure echo whisper',
  'soul smile sky journey song voice dreamer',
  'whisper cloudy dance story happy sky',
  'smile star laugh',
  'spark adventure mountain happy',
  'secret whisper flower fire hope light fire',
  'river path running dream',
  'forest path dance',
  'mountain wind dance rain journey cloud bright',
  'spark future adventure',
  'rain dreamer dance bright fire',
  'path song secret moment music',
  'voice mountain song secret sunset magic',
  'fire voice friend voice river hope fire',
  'journey friend cloud',
  'secret coffee glow future',
  'stone story river',
  'coffee mountain tree',
  'dreamer story soul',
  'ocean shadow time dream dream wonder laugh',
  'running adventure fire flower',
  'magic fire wonder friend heart hope',
  'stone memory coffee',
  'dreamer shadow shadow',
  'future storm coffee light happy dance',
  'tree song moment',
  'star fire tree moment secret',
  'echo stone dreamer spark secret fire laugh',
  'spark hope laugh river coffee cloudy star',
  'running sky sky story',
  'dance path voice',
  'cloud dream path',
  'running spark tree whisper glow',
  'sky cloud light rain dreamer sky stone',
  'dreamer path rain stone future hope',
  'mountain storm star',
  'dance storm flower adventure',
  'future spark memory dreamer',
  'wind music ocean echo',
  'soul star shadow',
  'magic music smile rain rain memory adventure',
  'path dream echo heart',
  'running cloudy story whisper',
  'magic fire friend story river',
  'heart heart journey',
  'whisper moment song',
  'sunset soul cloud friend hope cloud',
  'dream spark shadow soul',
  'shadow dreamer soul path',
  'rain blue fire star dreamer',
  'future laugh laugh smile tree flower smile',
  'laugh bright rain whisper cloud story',
  'future rain soul',
  'moment wonder wonder voice forest',
  'song voice glow stone wind ocean magic',
  'voice storm secret ocean sunset flower',
  'story adventure blue blue heart',
  'flower hope moment glow time',
  'river shadow echo dance adventure',
  'song blue ocean magic cloudy',
  'song happy memory glow ocean',
  'story echo memory soul cloudy glow',
  'glow whisper future secret',
  'friend echo journey shadow light shadow blue',
  'voice forest laugh',
  'journey spark forest smile',
];

const coloradoRoomId = '9Q5yMi8VkkZZCoZeevEQZ';

console.log('running simulation');
console.log('fetching user data');

const userIds = await db
  .select({ id: users.id })
  .from(users)
  .then(us => {
    console.log(us);
    return us.map(u => u.id);
  });

const numUsers = userIds.length;
const numPhrases = randomChatGptGeneratedPhrases.length;

console.log(`${numUsers} users found`);

console.log(`Sending chats every 2 seconds to http://localhost:3000/rooms/${coloradoRoomId}/chats...`);

setInterval(async () => {
  const randomIndex = Math.floor(Math.random() * numPhrases);
  const phrase = randomChatGptGeneratedPhrases[randomIndex];
  const randomUserIdIndex = Math.floor(Math.random() * numUsers);
  const userId = userIds[randomUserIdIndex];

  console.log(`posting for user "${userId}" the phrase "${phrase}"`);
  // why is this failing?
  try {
    const response = await fetch(`http://localhost:3000/rooms/${coloradoRoomId}/chats`, {
      body: JSON.stringify({ text: randomChatGptGeneratedPhrases[randomIndex] }),
      headers: { Accept: '*/*', Authorization: `Bearer ${userId}`, 'Content-Type': 'application/json' },
      method: 'POST',
    }).then(r => r.json());
    console.log('chat sent.', response);
  } catch (e) {
    console.log('chat failed.', (e as Error).message);
  }
}, 2000);
